
name: CI/CD with docker

on:
  push:
    branches: [ main ]

env:
  API_IMG_TEST: "ghcr.io/git-compendium/ci-docker/api:test"
  API_IMG_STABLE: "ghcr.io/git-compendium/ci-docker/api:latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t "${API_IMG_TEST}" .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push docker image
        run: docker push "${API_IMG_TEST}"
  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      api:
        # stupid: cannot be a variable name
        image: ghcr.io/git-compendium/ci-docker/api:test
        ports:
          - 3001:3001
    steps:
      - uses: actions/checkout@v2
      - name: test running container
        run: |
          npm install
          npm test
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Tag docker image
        run: |
          echo "your variables: ${API_IMG_TEST} ${API_IMG_STABLE}"
          docker tag "${API_IMG_TEST}" "${API_IMG_STABLE}"
